name: mcmc
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - nvidia/label/cuda-12.1.1::cuda-toolkit=12.1
  - plyfile
  - python=3.10
  - pytorch=2.5.1
  - torchaudio
  - torchvision
  - pip:
    - git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e
    - viser
    - nerfview==0.0.2
    - "imageio[ffmpeg]"
    - torchmetrics[image]
    - tyro>=0.8.8
    - tqdm
    - numpy<2.0.0
    - scikit-learn
    - opencv-python
    - pillow
    - tensorboard
    - tensorly
    - pyyaml
    - matplotlib
    - git+https://github.com/rahul-goel/fused-ssim@1272e21a282342e89537159e4bad508b19b34157
    - submodules
