name: mcmc
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - gcc=12
  - nvidia/label/cuda-12.4.1::cuda-toolkit
  - plyfile
  - python=3.10
  - pytorch=2.5.1
  - torchaudio
  - torchvision
  - pip:
    - .
